student_name=["Tahir", "Shahil", "Huzaifa", "Denil","Yassir"]
print(student_name)
print(student_name[0])
print(student_name[1])
print(student_name[2])
print(student_name[3])
print(student_name[4])
(student_name.append("test"))
(student_name.append("test1"))
print(student_name[5])
print(student_name[6])
print(student_name)
student_name.sort()
print(student_name)
