#import time
print ("Please type your name!")
name=input()
print("Nice to see you " +name)
print ("So " +name +" ,what is your favourite food?")
food=input()
print("So your favourite food is " +food)
print("Thanks for telling me, Where do you live?")
live=input()
print("So you live in "+live)
#time.sleep(1)
print("So your name is "+name +", your favourite food is "+food +" and you live in "+live)
